# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe3d6d078fb8c235a0f68c36669555261fb3738652a2976387cdf531a44f4089daad20b4c8e5cfa03ff6c71bd90315f4d7c93a7fd559f88a8f87653f6da5630

test:
  secret_key_base: 285b48fec840daad12ad2b1d45b76f8e41d14c848a433c9db719f95157eaed5b2eaced63395af289116b460bd3e56ec5675fe83a386f7037636b12e381a23edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
